### ISSUE TITLE
Formato padrão dos requisitos

### ISSUE THREAD

**Issue by ygorcanalli** [cp2-dc-info-projeto-final-2018/requisitos-alexandr-ia#6]
Os requisitos não estão no padrão apresentado no tutorial. Por favor verifiquem o arquivo [requisitos.md](https://github.com/cp2-dc-info-projeto-final-2018/exemplo-requisitos/blob/master/requisitos.md) de exemplo.

**Comment by CarlosEduardoValladares** [comment]
Consertado :)
